<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cmb_intermediario</name>
   <tag></tag>
   <elementGuidId>ed540682-3960-408c-9fd3-0a4a732868f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '7487710' or . = '7487710') and @ref_element = 'Object Repository/ESPACIO/Page_Portal Tradicional/iframe_InicioCotizacin y EmisinIndividualAu_a0ceff']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-alineacion > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id=&quot;guardar_agente&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>275d5130-c244-48b6-acf6-4bddae27f7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7487710</value>
      <webElementGuid>034f22d4-776c-46a9-808b-c25a3e20bfe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-4&quot;)/app-alertas[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-dialog-content&quot;]/div[@class=&quot;text-alineacion&quot;]/span[1]</value>
      <webElementGuid>3aa2e1d2-96ad-4fc4-b29f-0cae3b30e5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPACIO/GLOBALES/iframe</value>
      <webElementGuid>37428603-dd01-4639-93ad-8309f8779eb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-4']/app-alertas/div[2]/div/span</value>
      <webElementGuid>62343715-5ea7-453f-af2c-9b885c6aa377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[1]/preceding::span[1]</value>
      <webElementGuid>26509f91-89a5-4eb6-b2c8-b4db5773570f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-alertas/div[2]/div/span</value>
      <webElementGuid>89f4c38e-cd80-4cb5-aeba-47730da5cc2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '7487710' or . = '7487710')]</value>
      <webElementGuid>38524655-96db-44d7-8751-486e49502158</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
