<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_telefono</name>
   <tag></tag>
   <elementGuidId>0fe254f1-4ce0-42f3-b302-4ff949b2f702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guardar_telefono</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guardar_telefono']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dcdbe85-3232-400b-848e-603d4696bd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>e3add170-68ab-4753-bdd1-37db343d8620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contratanteTelefono</value>
      <webElementGuid>26cc4139-7f2a-4647-8178-24b03b7d6fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guardar_telefono</value>
      <webElementGuid>481180e1-21f2-4033-94e5-a0815155a526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Telefono:</value>
      <webElementGuid>28f32d17-68e5-4c09-885a-5423c53dd183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f72c46f7-d196-4308-adab-3cc46e2989bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1a039e32-a828-4cf3-af1d-dcf944b92167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guardar_telefono&quot;)</value>
      <webElementGuid>fbb85ae1-f63d-4c42-bbc3-8d1ee8ce43b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPACIO/GLOBALES/iframe</value>
      <webElementGuid>d4946533-7dac-4bb5-8838-11cfa5eff302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guardar_telefono']</value>
      <webElementGuid>4c8550a0-9603-431a-8c8c-8f4eca936a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-3']/app-guardar-tradicional/div[2]/form/table[2]/tbody/tr/td[2]/mat-form-field/div/div/div/input</value>
      <webElementGuid>4cfee4c3-b840-4f81-964c-73b7d52c72d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/mat-form-field/div/div/div/input</value>
      <webElementGuid>50f08e38-337d-49bf-8ae1-7d647dd406c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'guardar_telefono' and @placeholder = 'Telefono:']</value>
      <webElementGuid>81ad9547-d35f-4b38-95e8-6e54d082f3dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
