<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_apellidoMaterno</name>
   <tag></tag>
   <elementGuidId>8a645137-6374-4bb0-9491-4a0c513b2a6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guardar_materno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guardar_materno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d266bb65-57f4-4d0e-8f60-ffb1c5f5c3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3c9594be-7de6-481a-8674-0d5abb9aed9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contrApMaterno</value>
      <webElementGuid>19ac7359-f9da-4942-b4d0-604bb10c927d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guardar_materno</value>
      <webElementGuid>7a7be412-9ced-42cc-a096-8b042543d8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apellido materno:</value>
      <webElementGuid>24f9a2c0-738f-47bd-ba90-979568571d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f7107c71-73d1-47c7-b393-519bef64d840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>57129035-3677-4df4-989f-48934a7f32f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guardar_materno&quot;)</value>
      <webElementGuid>da20dba2-d0ae-4b3d-8a2e-bff726550936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPACIO/GLOBALES/iframe</value>
      <webElementGuid>edfe0b1b-ae47-4152-8f42-fa010f628a9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guardar_materno']</value>
      <webElementGuid>4135437a-8207-4c7a-968b-03a8e1220fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-3']/app-guardar-tradicional/div[2]/form/div[2]/div[2]/mat-form-field/div/div/div/input</value>
      <webElementGuid>e1ed5a81-5a84-44a2-bb97-71c8f15f9031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div[2]/mat-form-field/div/div/div/input</value>
      <webElementGuid>4059c71a-9f0e-47b9-8fb8-4928da5f85c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'guardar_materno' and @placeholder = 'Apellido materno:']</value>
      <webElementGuid>e895a1c2-6f04-4b09-af4c-16ea8de2c960</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
