<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_lada</name>
   <tag></tag>
   <elementGuidId>2753678d-06a3-446c-afe4-71c592388438</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guardar_lada</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guardar_lada']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0f6d9fb-deb3-4ed4-9668-1e27122a10a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>edd20ef3-ff6e-44ca-86d9-b97a47d500a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contratanteLada</value>
      <webElementGuid>499f9756-75ff-49b3-a6f7-676950b3a1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guardar_lada</value>
      <webElementGuid>94ae4a0e-932c-4451-bd17-50dd7548ade7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Lada:</value>
      <webElementGuid>16a161d7-5978-4008-88cb-c486fc39276b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2a1021d-9c22-4edb-ac7c-f1f793fe53e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9726f2d9-3676-4ec5-bbd8-f1ffe06ca064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guardar_lada&quot;)</value>
      <webElementGuid>bc281741-db8f-4b38-856a-9128aaedafe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPACIO/GLOBALES/iframe</value>
      <webElementGuid>919ec26d-deef-4f1a-88ae-72c7dbb299e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guardar_lada']</value>
      <webElementGuid>0eb3a266-77d8-4c7c-b98b-0700fe604951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-3']/app-guardar-tradicional/div[2]/form/table[2]/tbody/tr/td/mat-form-field/div/div/div/input</value>
      <webElementGuid>e6003b87-2ace-4e04-99e3-296d2f05d7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td/mat-form-field/div/div/div/input</value>
      <webElementGuid>ff1ee691-fe5c-4814-bf6c-7cf7caed41ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'guardar_lada' and @placeholder = 'Lada:']</value>
      <webElementGuid>67bbd8d6-9267-43cf-a9b7-9d89d8ea51b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
