<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_apellidoPaterno</name>
   <tag></tag>
   <elementGuidId>e90dc025-cb91-439e-b8b7-60d10248a58f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guardar_paterno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guardar_paterno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc9f75d4-81fb-4172-8ecd-d5174a377d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d75a8e96-ebdc-40ae-9493-a16fb8e3be7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contrApPaterno</value>
      <webElementGuid>866f3955-83ed-49bc-bc5f-e32fe0129142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guardar_paterno</value>
      <webElementGuid>02f57d63-c256-4319-acfc-373c698b58b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apellido paterno:</value>
      <webElementGuid>fd456790-70c6-483a-910e-a11a7f5aa256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9de8d8af-3d80-4f81-abca-7e0ac72a89c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0cd9dcb8-2188-4e34-b37d-e36f42a88f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guardar_paterno&quot;)</value>
      <webElementGuid>325e9392-a877-4bb8-a00d-57b221682290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPACIO/GLOBALES/iframe</value>
      <webElementGuid>cab2767a-7f7f-493c-b425-2502f4abf7ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guardar_paterno']</value>
      <webElementGuid>d5069360-a0ec-4158-bf0e-bc1dddddaff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-3']/app-guardar-tradicional/div[2]/form/div[2]/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>658aa160-0820-4879-9ffa-c302a9842e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>e8db6e05-4662-4d2e-b951-51e5987a488d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'guardar_paterno' and @placeholder = 'Apellido paterno:']</value>
      <webElementGuid>d9c85e96-f52a-40ab-b492-48a51e743ffa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
