<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_referencia</name>
   <tag></tag>
   <elementGuidId>3392f3bf-2592-48cd-96c8-39fe686461c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guardar_referencia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guardar_referencia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4190496a-c9c0-4fd4-a93a-9c68556f9766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>749fdff7-70ca-44ec-b911-61d109ea9653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>referencia</value>
      <webElementGuid>bf45253b-2d5c-49e3-8fcf-082025c62b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guardar_referencia</value>
      <webElementGuid>1b950315-7620-4cfd-86ba-b710079b53c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Capturar Referencia:</value>
      <webElementGuid>e6300616-82b9-4a03-a97e-54eb9a3f5251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9cbf15c-a1dd-4996-a356-ff76969fefe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4263f2f5-3703-412e-802d-cd85b07db219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guardar_referencia&quot;)</value>
      <webElementGuid>f7fd9173-0165-43e8-a0af-5781d075e6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPACIO/GLOBALES/iframe</value>
      <webElementGuid>4503264b-a637-4314-8027-1f9ec9f84629</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guardar_referencia']</value>
      <webElementGuid>64b7e0ec-d964-41e4-b6e6-23084cdd8af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-3']/app-guardar-tradicional/div[2]/form/mat-form-field[3]/div/div/div/input</value>
      <webElementGuid>115722cb-cfa2-4432-b692-c4c0891b9425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[3]/div/div/div/input</value>
      <webElementGuid>af165a01-5981-4e38-aa90-28518b2c9dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'guardar_referencia' and @placeholder = 'Capturar Referencia:']</value>
      <webElementGuid>e59d8f4d-e662-4e04-8e27-60432d689130</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
