<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_apellidoPaterno</name>
   <tag></tag>
   <elementGuidId>b7645612-8b7c-4c9b-bbef-22b2b15218e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name=&quot;apellidoPaterno&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#guardar_paterno</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46a16d74-13d7-4345-a747-5bc93297d103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>cfcf4712-be59-4256-9e17-0fde2ae4ae96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contrApPaterno</value>
      <webElementGuid>aa107aa4-88ea-4ec6-a1b9-fe9fd0a329ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guardar_paterno</value>
      <webElementGuid>aca17e56-dd00-4287-aee7-9418013a94a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apellido paterno:</value>
      <webElementGuid>0c3d0e85-dc87-46e8-9525-c00cfc0157ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>26f0f670-c2c6-46cf-997f-efb0f04f4f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>532d4e54-d94b-4519-b53a-03b55a180f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guardar_paterno&quot;)</value>
      <webElementGuid>f36eddd5-13e2-4d6a-893e-21ba4816eb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ESPACIO/GLOBALES/iframe</value>
      <webElementGuid>732cbaab-aa63-436c-bf7a-b53b5e7e6f3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guardar_paterno']</value>
      <webElementGuid>1e50d77d-02de-4190-b494-82a79db52143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-3']/app-guardar-tradicional/div[2]/form/div[2]/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>06b34653-92ca-4484-9edc-81c5f3a19c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>9446059d-eb9a-4a80-8ec6-bef418166aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'guardar_paterno' and @placeholder = 'Apellido paterno:']</value>
      <webElementGuid>2f0f6c75-041f-4863-9b4d-136eebd6da54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
